[workspace]
resolver = "2"
members = [
    "waves",
    "single-thread-executor",
]
default-members = [
    "waves",
    "single-thread-executor",
]

[profile.release]
debug = true
opt-level = "s"
lto = true
